/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description liveness — 프로세스가 살아 있는지만. DB를 보지 않는다 (DB 장애로 앱까지 재시작되면 안 된다).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description readiness — DB에 닿을 때만 트래픽을 받는다.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flavor-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flavor Tags */
        get: operations["flavor_tags_api_flavor_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Beans */
        get: operations["list_beans_api_beans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beans/{bean_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bean */
        get: operations["get_bean_api_beans__bean_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beans/{bean_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Similar Beans */
        get: operations["get_similar_beans_api_beans__bean_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brews */
        get: operations["list_brews_api_brews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/{brew_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brew */
        get: operations["get_brew_api_brews__brew_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grinders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grinders */
        get: operations["list_grinders_api_grinders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grinders/{grinder_id}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_api_grinders__grinder_id__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grinders/{grinder_id}/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest Grinder Clicks */
        get: operations["suggest_grinder_clicks_api_grinders__grinder_id__suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog */
        get: operations["list_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Recommendations */
        get: operations["latest_recommendations_api_recommendations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 프론트의 관리자 UI 표시용. 화면 숨김은 편의일 뿐, 실제 차단은 require_admin이 한다.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/beans/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Bean
         * @description 봉투 사진 → 원두 정보 초안. 저장하지 않는다 — 사람이 확인·수정한 뒤 POST /beans로 저장한다.
         */
        post: operations["extract_bean_api_admin_beans_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/beans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Bean */
        post: operations["create_bean_api_admin_beans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/beans/{bean_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Bean */
        put: operations["update_bean_api_admin_beans__bean_id__put"];
        post?: never;
        /** Delete Bean */
        delete: operations["delete_bean_api_admin_beans__bean_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grinders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Grinder */
        post: operations["create_grinder_api_admin_grinders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grinders/{grinder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Grinder */
        put: operations["update_grinder_api_admin_grinders__grinder_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Brew */
        post: operations["create_brew_api_admin_brews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews/{brew_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Brew */
        put: operations["update_brew_api_admin_brews__brew_id__put"];
        post?: never;
        /** Delete Brew */
        delete: operations["delete_brew_api_admin_brews__brew_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews/suggest-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Brew Tags */
        post: operations["suggest_brew_tags_api_admin_brews_suggest_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grind/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Grind Preview
         * @description 저장하지 않는 미리보기.
         */
        post: operations["analyze_grind_preview_api_admin_grind_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grind/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Measurement */
        post: operations["create_measurement_api_admin_grind_measurements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grind/measurements/{measurement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Measurement */
        delete: operations["delete_measurement_api_admin_grind_measurements__measurement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Collect */
        post: operations["run_collect_api_admin_catalog_collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/recommendations/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_admin_recommendations_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeanDraft */
        BeanDraft: {
            /** Name */
            name: string | null;
            /** Roaster */
            roaster: string | null;
            /** Country */
            country: string | null;
            /** Region */
            region: string | null;
            /** Variety */
            variety: string | null;
            /** Processing */
            processing: string | null;
            /** Roast Level */
            roast_level: string | null;
            /** Bag Flavor Notes */
            bag_flavor_notes: string[];
        };
        /** BeanDraftOut */
        BeanDraftOut: {
            draft: components["schemas"]["BeanDraft"];
            /** Filled Fields */
            filled_fields: number;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** BeanIn */
        BeanIn: {
            /** Name */
            name: string;
            /** Roaster */
            roaster?: string | null;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** Variety */
            variety?: string | null;
            /** Processing */
            processing?: string | null;
            /** Roast Level */
            roast_level?: string | null;
            /** Bag Flavor Notes */
            bag_flavor_notes?: string[];
        };
        /** BeanOut */
        BeanOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Roaster */
            roaster: string | null;
            /** Country */
            country: string | null;
            /** Region */
            region: string | null;
            /** Variety */
            variety: string | null;
            /** Processing */
            processing: string | null;
            /** Roast Level */
            roast_level: string | null;
            /** Bag Flavor Notes */
            bag_flavor_notes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BeanStatsOut */
        BeanStatsOut: {
            bean: components["schemas"]["BeanOut"];
            /** Brew Count */
            brew_count: number;
            /** Avg Rating */
            avg_rating: number | null;
        };
        /** BeanSummary */
        BeanSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Roaster */
            roaster: string | null;
        };
        /** Body_analyze_grind_preview_api_admin_grind_analyze_post */
        Body_analyze_grind_preview_api_admin_grind_analyze_post: {
            /** File */
            file: string;
            /** Marker Mm */
            marker_mm?: number | null;
            /** Mm Per Px */
            mm_per_px?: number | null;
        };
        /** Body_create_measurement_api_admin_grind_measurements_post */
        Body_create_measurement_api_admin_grind_measurements_post: {
            /** File */
            file: string;
            /** Brew Id */
            brew_id?: number | null;
            /** Grinder Id */
            grinder_id?: number | null;
            /** Clicks */
            clicks?: number | null;
            /** Marker Mm */
            marker_mm?: number | null;
            /** Mm Per Px */
            mm_per_px?: number | null;
        };
        /** Body_extract_bean_api_admin_beans_extract_post */
        Body_extract_bean_api_admin_beans_extract_post: {
            /** File */
            file: string;
        };
        /** BrewIn */
        BrewIn: {
            /** Bean Id */
            bean_id: number;
            /** Grinder Id */
            grinder_id?: number | null;
            /** Brewed On */
            brewed_on?: string | null;
            /** Grind Clicks */
            grind_clicks?: number | null;
            /** Water Temp C */
            water_temp_c?: number | null;
            /** Dose G */
            dose_g?: number | null;
            /** Water G */
            water_g?: number | null;
            /** Brew Time S */
            brew_time_s?: number | null;
            /** Rating */
            rating: number;
            /** Flavor Tags */
            flavor_tags?: string[];
            /** Note */
            note?: string | null;
        };
        /** BrewOut */
        BrewOut: {
            /** Id */
            id: number;
            bean: components["schemas"]["BeanSummary"];
            /** Grinder Id */
            grinder_id: number | null;
            /**
             * Brewed On
             * Format: date
             */
            brewed_on: string;
            /** Grind Clicks */
            grind_clicks: number | null;
            /** Water Temp C */
            water_temp_c: number | null;
            /** Dose G */
            dose_g: number | null;
            /** Water G */
            water_g: number | null;
            /** Brew Time S */
            brew_time_s: number | null;
            /** Rating */
            rating: number;
            /** Flavor Tags */
            flavor_tags: string[];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Measurements */
            measurements: components["schemas"]["GrindMeasurementOut"][];
            /**
             * Ratio
             * @description 원두 1g당 물 g.
             */
            readonly ratio: number | null;
        };
        /** CalibrationOut */
        CalibrationOut: {
            /** Grinder Id */
            grinder_id: number;
            /** Rows */
            rows: components["schemas"]["CalibrationRowOut"][];
            /** Monotonic */
            monotonic: boolean;
        };
        /** CalibrationRowOut */
        CalibrationRowOut: {
            /** Clicks */
            clicks: number;
            /** N */
            n: number;
            /** D50 Median Mm */
            d50_median_mm: number;
            /** D50 Min Mm */
            d50_min_mm: number;
            /** D50 Max Mm */
            d50_max_mm: number;
        };
        /** CatalogBeanOut */
        CatalogBeanOut: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Price */
            price: string | null;
            /** Available */
            available: boolean;
            /** Status */
            status: string;
            /** Country */
            country: string | null;
            /** Processing */
            processing: string | null;
            /** Normalized */
            normalized: {
                [key: string]: unknown;
            } | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** ClickSuggestionOut */
        ClickSuggestionOut: {
            /** Grinder Id */
            grinder_id: number;
            /** Target D50 Mm */
            target_d50_mm: number;
            /** Clicks */
            clicks: number | null;
            /** Reason */
            reason: string;
        };
        /** CollectResultOut */
        CollectResultOut: {
            /** Fetched */
            fetched: number;
            /** New */
            new: number;
            /** Updated */
            updated: number;
            /** Normalized */
            normalized: number;
            /** Skipped */
            skipped: number;
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Errors */
            errors: string[];
        };
        /** FlavorTagOut */
        FlavorTagOut: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Group Label */
            group_label: string;
            /** Label */
            label: string;
        };
        /** GrindAnalysisOut */
        GrindAnalysisOut: {
            /** Particle Count */
            particle_count: number;
            /** Mm Per Px */
            mm_per_px: number;
            /** D10 Mm */
            d10_mm: number;
            /** D50 Mm */
            d50_mm: number;
            /** D90 Mm */
            d90_mm: number;
            /** Count D50 Mm */
            count_d50_mm: number;
            /** Min Detectable Mm */
            min_detectable_mm: number;
            /** Clump Suspects */
            clump_suspects: number;
            /** Histogram */
            histogram: components["schemas"]["HistogramBinOut"][];
            /** Warnings */
            warnings: string[];
            /** Count D10 Mm */
            count_d10_mm: number;
            /** Count D90 Mm */
            count_d90_mm: number;
        };
        /** GrindMeasurementOut */
        GrindMeasurementOut: {
            /** Particle Count */
            particle_count: number;
            /** Mm Per Px */
            mm_per_px: number;
            /** D10 Mm */
            d10_mm: number;
            /** D50 Mm */
            d50_mm: number;
            /** D90 Mm */
            d90_mm: number;
            /** Count D50 Mm */
            count_d50_mm: number;
            /** Min Detectable Mm */
            min_detectable_mm: number;
            /** Clump Suspects */
            clump_suspects: number;
            /** Histogram */
            histogram: components["schemas"]["HistogramBinOut"][];
            /** Warnings */
            warnings: string[];
            /** Id */
            id: number;
            /** Brew Id */
            brew_id: number | null;
            /** Grinder Id */
            grinder_id: number;
            /** Clicks */
            clicks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GrinderIn */
        GrinderIn: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** GrinderOut */
        GrinderOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBinOut */
        HistogramBinOut: {
            /** Lo Mm */
            lo_mm: number;
            /** Hi Mm */
            hi_mm: number;
            /** Count */
            count: number;
            /** Area Share */
            area_share: number;
        };
        /** MeOut */
        MeOut: {
            /** Uid */
            uid: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** Page[BeanOut] */
        Page_BeanOut_: {
            /** Items */
            items: components["schemas"]["BeanOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[BrewOut] */
        Page_BrewOut_: {
            /** Items */
            items: components["schemas"]["BrewOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[CatalogBeanOut] */
        Page_CatalogBeanOut_: {
            /** Items */
            items: components["schemas"]["CatalogBeanOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** RecommendationItemOut */
        RecommendationItemOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "my_bean" | "catalog";
            /** Ref Id */
            ref_id: number;
            /** Title */
            title: string;
            /** Similarity */
            similarity: number;
            /** Reason */
            reason: string;
            /**
             * Reason Source
             * @enum {string}
             */
            reason_source: "llm" | "template";
            /** Evidence Brew Ids */
            evidence_brew_ids: number[];
            start_grind: components["schemas"]["StartGrindOut"] | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** RecommendationSnapshotOut */
        RecommendationSnapshotOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Embedding Model */
            embedding_model: string;
            /** Llm Model */
            llm_model: string | null;
            /** Profile Brew Ids */
            profile_brew_ids: number[];
            /** Items */
            items: components["schemas"]["RecommendationItemOut"][];
        };
        /** SimilarBeanOut */
        SimilarBeanOut: {
            bean: components["schemas"]["BeanOut"];
            /** Similarity */
            similarity: number;
            /** Brew Count */
            brew_count: number;
            /** Avg Rating */
            avg_rating: number | null;
        };
        /** StartGrindOut */
        StartGrindOut: {
            /** D50 Mm */
            d50_mm: number;
            /** Grinder Id */
            grinder_id: number;
            /** Clicks */
            clicks: number | null;
            /** Reason */
            reason: string;
        };
        /** TagSuggestIn */
        TagSuggestIn: {
            /** Note */
            note: string;
        };
        /** TagSuggestOut */
        TagSuggestOut: {
            /** Tags */
            tags: string[];
            /** Dropped */
            dropped: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    flavor_tags_api_flavor_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlavorTagOut"][];
                };
            };
        };
    };
    list_beans_api_beans_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BeanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bean_api_beans__bean_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bean_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeanStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similar_beans_api_beans__bean_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                bean_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarBeanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brews_api_brews_get: {
        parameters: {
            query?: {
                bean_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BrewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brew_api_brews__brew_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grinders_api_grinders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderOut"][];
                };
            };
        };
    };
    get_calibration_api_grinders__grinder_id__calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grinder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_grinder_clicks_api_grinders__grinder_id__suggest_get: {
        parameters: {
            query: {
                target_d50_mm: number;
            };
            header?: never;
            path: {
                grinder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClickSuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalog_api_catalog_get: {
        parameters: {
            query?: {
                include_unavailable?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CatalogBeanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_recommendations_api_recommendations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationSnapshotOut"] | null;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    extract_bean_api_admin_beans_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_bean_api_admin_beans_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeanDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bean_api_admin_beans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bean_api_admin_beans__bean_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bean_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bean_api_admin_beans__bean_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bean_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_grinder_api_admin_grinders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrinderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_grinder_api_admin_grinders__grinder_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grinder_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrinderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brew_api_admin_brews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_brew_api_admin_brews__brew_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_brew_api_admin_brews__brew_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_brew_tags_api_admin_brews_suggest_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagSuggestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSuggestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_grind_preview_api_admin_grind_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_grind_preview_api_admin_grind_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrindAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_measurement_api_admin_grind_measurements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_measurement_api_admin_grind_measurements_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrindMeasurementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_measurement_api_admin_grind_measurements__measurement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measurement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_collect_api_admin_catalog_collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectResultOut"];
                };
            };
        };
    };
    refresh_api_admin_recommendations_refresh_post: {
        parameters: {
            query?: {
                country?: string | null;
                processing?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
